plugins {
    id 'java-library'
    id 'io.qameta.allure' version '2.12.0'
}

repositories {
    mavenCentral()
}

def allureVersion = "2.21.0"

dependencies {
    testImplementation("com.codeborne:selenide:7.0.4") {
        exclude group: 'org.yaml', module: 'snakeyaml'
    }
    testImplementation('com.github.javafaker:javafaker:1.0.2') {
        exclude group: 'org.yaml', module: 'snakeyaml'
    }
    testImplementation(
            "org.junit.jupiter:junit-jupiter:5.10.1",
            'org.slf4j:slf4j-simple:2.0.9',
            'org.yaml:snakeyaml:2.0',
            "io.qameta.allure:allure-selenide:$allureVersion"
    )
}

test {
    useJUnitPlatform()

    test {
        useJUnitPlatform()

        test {
            useJUnitPlatform()

            systemProperty "browser", project.hasProperty('browser') ? project.browser : "chrome"
            systemProperty "browser.version", project.hasProperty('browser.version') ? project.browser.version : "latest"
            systemProperty "browser.size", project.hasProperty('browser.size') ? project.browser.size : "1920x1080"
            systemProperty "SELENOID_URL", project.hasProperty('SELENOID_URL') ? project.SELENOID_URL : "http://localhost:4444/wd/hub"
        }

    }

allure {
    report {
        version.set(allureVersion)
    }
    adapter {
        frameworks {
            junit5 {
                adapterVersion.set(allureVersion)
            }
        }
    }
}
}